services:
  dev:
    image: lunarzdev/epsilon-sitl:mac
    build:
      args:
        TARGET_PLATFORM: mac
    environment:
      DISPLAY: host.docker.internal:0
    volumes: []
  sitl:
    image: lunarzdev/epsilon-sitl:mac
    environment:
      DISPLAY: host.docker.internal:0
    volumes:
      - ./boat.param:/param/boat.param:ro