services:
  dev:
    image: lunarzdev/epsilon-dev:windows
    build:
      args:
        TARGET_PLATFORM: windows
    environment:
      DISPLAY: host.docker.internal:0
    volumes: []
  sitl:
    image: lunarzdev/epsilon-sitl:windows
    environment:
      DISPLAY: host.docker.internal:0
    volumes:
      - ./boat.param:/param/boat.param:ro