services:
  dev:
    image: lunarzdev/epsilon-dev:rpi
    build:
      args:
        TARGET_PLATFORM: rpi
    environment:
      DISPLAY: host.docker.internal:0
    volumes: []
  sitl:
    image: lunarzdev/epsilon-sitl:rpi
    environment:
      DISPLAY: host.docker.internal:0
    volumes:
      - ./boat.param:/param/boat.param:ro
